### PR TITLE
Jacqueline Binya GSOD-2020 Application

### PR DESCRIPTION
**Pull request by JackieBinya**
Signed-off-by: JackieBinya <jacquelinebinya@gmail.com>

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @JackieBinya 
 Can you please resolve the merge conflicts if possible?

Let me know if you need any help. :slightly_smiling_face:

**Comment by JackieBinya** [comment]
@vchrombie 
May you please review my commit, I am not sure if I was able to do what you requested.
Thanks.

**Comment by vchrombie** [comment]
Thanks @JackieBinya 
It looks perfect. :slightly_smiling_face:

**Comment by GeorgLink** [comment]
Thanks @JackieBinya  and @vchrombie

**Pull request merged**
