### PR TITLE
add information about @inishchith

### PR DESCRIPTION
**Pull request by inishchith**
Hello everyone, I am Nishchith Shetty ( [inishchith](http://github.com/inishchith) ) and I am interested in the project: Support of Source Code Related Metrics

- [X] I am adding my information to the list of interested students through this PR.
- [X] I've added link to my Microtasks repository 

I'll update this thread and the commit with link to the proposal, once i have it ready.

Looking forward to working with you guys!

Thanks

### CODE REVIEW

**Comment by GeorgLink** [comment]
By the way, good job on the sign-off :)

**Comment by inishchith** [comment]
> You may link to a google doc that is not finished yet and complete it before the end of the application period.

Yeah. Sure, I'll add them in some time ;)

**Comment by Polaris000** [comment]
Is it necessary to send a pull request to governance with my information before the start of the student application process? As I have n't finished my proposal yet, can I wait until my proposal is ready and send everything all at once (during the student application process)?
Though the answer might be obvious, better safe than sorry!
@GeorgLink

**Comment by GeorgLink** [comment]
Hi @Polaris000,

Good question and I'd be happy to answer it. However, it does not relate to this specific pull request and would better be asked and answered as a separate issue or - even better - on the mailing list. Can you please ask the question in a separate issue or on the mailing list?

Thanks,
Georg

**Comment by inishchith** [comment]
@GeorgLink I've updated the link to my proposal, I'll make sure it gets completed in some time. 
Thanks.

**Comment by inishchith** [comment]
@GeorgLink Please do review this. I've added the link to my proposal.
Thanks :)

**Pull request merged**
