### PR TITLE
Adopt Code of Conduct

### PR DESCRIPTION
**Pull request by GeorgLink**
**IMPORTANT: Do not merge, until the CHAOSS Governance Board has formally adopted the Code of Conduct for the CHAOSS community.**

The Code of Conduct workgroup is finalizing the text of a Code of Conduct that will be proposed to the CHAOSS community.

The Contributor Covenant has most of our desired features and is the basis of our own Code of Conduct.

We added a paragraph from Geek Feminism about the reporting and consequences. (paragraph starting with "We will respect confidentiality")

We added a paragraph about reporting yearly incidence report numbers and reviewing the CoC. (paragraph starting with "The CHAOSS Governance Board will")

### CODE REVIEW

**Comment by GeorgLink** [comment]
fixes chaoss/metrics#26

**Comment by GeorgLink** [comment]
The CHAOSS Working Group for a Code of Conduct recommends to the CHAOSS Governing Board to adopt for the CHAOSS Community the Code of Conduct in this pull-request. The working group further proposes that the Governing Board shall review the effectiveness of the Code of Conduct every year when the Code of Conduct Team provides the yearly statistic of reports.

In adopting this Code of Conduct, two things need to occur:
1. The community needs to elect a Code of Conduct Team with 4 members.
2. An email address needs to be created -- e.g. coc@chaoss.community -- that gets forwarded to only the four elected Code of Conduct Team members and can be used for incidence reports.

**Comment by GeorgLink** [comment]
Yes, please discuss and vote on this proposal at the next Governing Board meeting.

**Comment by GeorgLink** [comment]
NOTE: Please add the date of the GB vote before squash-merging.

I added a version history to the document and it includes the date of the GB vote for completeness.

**Comment by germonprez** [comment]
Is the question, when is the board voting? If so, Feb 12th.

**Comment by GeorgLink** [comment]
No question, just a note that we need to update before merging. Thanks for the update though.

**Comment by GeorgLink** [comment]
Thanks @jgbarah

**Comment by GeorgLink** [comment]
Document of the working group including the evaluation results of code of conducts: <https://docs.google.com/document/d/12NVJnFccSapPKK_f5a7HjwgQ4VP2ws9Sn1IG2t8ha4g/edit?usp=sharing>

**Comment by GeorgLink** [comment]
The GB has approved this Code of Conduct today.

**Pull request merged**
