### PR TITLE
Update GSoC-interest.md

### PR DESCRIPTION
**Pull request by apoorvkhare07**

### CODE REVIEW

**Comment by apoorvkhare07** [comment]
@GeorgLink Can u please merge this too ?

**Comment by GeorgLink** [comment]
Duplicate of #51 ?

**Comment by apoorvkhare07** [comment]
@GeorgLink No this is for a different project

**Comment by GeorgLink** [comment]
Which project do you want to propose, this one or the other? Please propose only one.

**Comment by apoorvkhare07** [comment]
Is it that I can't make proposal for two different projects ?

**Comment by GeorgLink** [comment]
This is for the CHAOSS project and you can only work on one idea, so please
choose which idea you want to propose.

**Comment by apoorvkhare07** [comment]
Ok then, I'll go with the one already proposed. 
And leave this one.

**Comment by GeorgLink** [comment]
​Sounds good. Thank you!

**Pull request closed without merging**
