### PR TITLE
Proposal for a text on how we make decisions

### PR DESCRIPTION
**Pull request by jgbarah**
After some discussion in the mailing list (see [1] [2] for conclusions, and whole thread [3] [4] for context), I've drafted this proposal which hopefully captures the result of that discussion.

Any feedback is welcome.

[1] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000173.html

[2] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000186.html

[4] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000157.html

[3] https://lists.linuxfoundation.org/pipermail/chaoss/2018-November/000169.html

### CODE REVIEW

**Comment by geekygirldawn** [comment]
This is still a bit ambiguous. I would prefer to make it clear that discussions happen in the calls, but that decisions are made on the mailing list.

Maybe a few edits:

* (line 69)The basic decision making mechanism for CHAOSS is [lazy consensus](http://www.apache.org/foundation/glossary.html#LazyConsensus), which occurs on the relevant mailing list. Each of the software projects or working groups will try to reach consensus on their decisions, after giving a reasonable opportunity to people contributing in them to express their opinion. When a discussion about a decision happens outside of the mailing list in the periodic calls or other communication channels, a proposal for a decision will be sent to the appropriate mailing list(s). The decision should be finalized on the mailing list using lazy consensus after giving people who were not in the discussion time to review, comment, and participate. 
* (line 71) When the issues under discussion are perceived to be of importance to the whole CHAOSS community, the same process will be carried on at the CHAOSS level, using the general periodic calls and other communication means for discussion with the final decision being made on the mailing list using lazy consensus.

**Comment by jgbarah** [comment]
Thanks, Dawn. I fully agree, your redaction is much better. I've added it to the pull request.

I've just added a note about lazy consensus, taking the wording from Apache, just to avoid problems if the link stop working for some reason.

**Comment by geekygirldawn** [comment]
This looks great, thank you!

**Comment by jgbarah** [comment]
@GeorgLink, let's thank Apache, I just copied and pasted from their definition, which includes the time frame. And yes, I also think it is a very good idea to specify a reasonable time frame.

**Pull request merged**
