### PR TITLE
Update Outreachy-ideas.md

### PR DESCRIPTION
**Pull request by vchrombie**
The ideas in the [Outreachy-ideas.md](https://github.com/chaoss/governance/blob/master/Outreachy-ideas.md) are not aligned with the ones listed on the [CHAOSS section on the website](https://www.outreachy.org/apply/project-selection/#chaoss). This PR removes the ideas from the doc which are not uploaded to the website.

@germonprez @GeorgLink, please check this when you are free.

### CODE REVIEW

**Comment by vchrombie** [comment]
I checked with the [Outreachy-interest.md](https://github.com/chaoss/governance/blob/master/Outreachy-interest.md). As of now, no one added themselves for the projects not listed on the website. So, I think it is not a problem. 

But, how about referencing this PR to all the ideas (issues here, so just #issue_number would create a reference over the idea), just to be on the safe side. 

Please check this [comment](https://github.com/chaoss/grimoirelab/issues/285#issuecomment-598415192).

**Comment by vchrombie** [comment]
@GeorgLink 
 
> But, how about referencing this PR to all the ideas (issues here, so just #issue_number would create a reference over the idea), just to be on the safe side.
> 
> Please check this [comment](https://github.com/chaoss/grimoirelab/issues/285#issuecomment-598415192).

WDYT?

**Comment by GeorgLink** [comment]
Go for it. I appreciate that you are thinking about how to communicate the change effectively to everyone who needs to know about it.

**Comment by vchrombie** [comment]
Ping.
https://github.com/chaoss/augur/issues/557
https://github.com/chaoss/augur/issues/558
https://github.com/chaoss/augur/issues/559
https://github.com/chaoss/grimoirelab/issues/286
https://github.com/chaoss/grimoirelab/issues/287
https://github.com/chaoss/grimoirelab/issues/288
https://github.com/badging/diversity-and-inclusion/issues/1

The Outreachy ideas have been updated. You can either view them on [Outreachy-ideas.md](https://github.com/chaoss/governance/blob/master/Outreachy-ideas.md) or on the [Outreachy website](https://www.outreachy.org/apply/project-selection/#chaoss).

Thanks.

**Pull request merged**
