### PR TITLE
Update GSoC-interest.md

### PR DESCRIPTION
**Pull request by theexplorist**

### CODE REVIEW

**Comment by theexplorist** [comment]
sir the proposal link branch is showing conflict

**Comment by GeorgLink** [comment]
you already added yourself in #47. Please update this pull requests (rebase) to not add yourself again but only update the proposal link.

**Comment by theexplorist** [comment]
sir so can i do it right now ?

**Comment by GeorgLink** [comment]
Yes, you simply commit the changes to your branch ``theexplorist-patch-1`` and it will update the pull request automatically.

**Comment by theexplorist** [comment]
sir i am not able to rebase it, can you please help me

**Comment by GeorgLink** [comment]
This should help: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by theexplorist** [comment]
sir do i have to squash also, is it necessary ?

**Comment by GeorgLink** [comment]
No, I can do the squash when I merge it.

**Comment by theexplorist** [comment]
sir i have applied what was written in documentation and its showing 
On branch theexplorist-patch-1
nothing to commit, working tree clean after resolving
but then also its not updating.

**Comment by GeorgLink** [comment]
You need to merge the latest changes from upstream  (i.e., the
chaoss/governance repository).

**Comment by theexplorist** [comment]
git push --set-upstream origin theexplorist-patch-1
u mean by this command ?

**Comment by GeorgLink** [comment]
@theexplorist 
I do not see your Google Summer of Code application. 
I close this pull request since we can only consider applicants who completed the official GSoC application.

**Pull request closed without merging**
