### PR TITLE
Update GSoD-interest.md

### PR DESCRIPTION
**Pull request by tharun143**
Adding my proposal link for GSoD 2020 to the table.

### CODE REVIEW

**Comment by germonprez** [comment]
@tharun143 could you please provide a DCO signature.

**Comment by vchrombie** [comment]
Thanks for PR @tharun143.
Just thought of giving a small hint.

You need not close the PR if you miss a sign-off for a commit, you can try this next time
```
$ git commit --amend --signoff
```

This would add the signoff to the previous commit.
I hope this helps. :smile:

**Comment by tharun143** [comment]
I thought if doing it. But I made the PR through Github. Is there any way to add the DCO signature through Github instead of adding `-s` to the command. @vchrombie If you know tell me pls. This would help me in the future.

**Comment by vchrombie** [comment]
> I thought if doing it. But I made the PR through Github. Is there any way to add the DCO signature through Github instead of adding `-s` to the command. @vchrombie If you know tell me pls. This would help me in the future.

Yes, you can do it in multiple ways. :grimacing: 

1. (easy) You can use this extension, [scottrigby/dco-gh-ui](https://github.com/scottrigby/dco-gh-ui)
2. (medium) While committing, you can add the sign-off string in the description box under the commit title
3. (hard) Clone the repository and the branch and sign-off using command and force push

:smile: 
You can always go for the first option. Just install the extension, it will take care of the sign-off.

**Comment by tharun143** [comment]
@vchrombie I tried the second one. But it didn't work for me. I will give another try 👍 Thanks 😄

**Pull request closed without merging**
