### PR TITLE
add GSoC-interested list

### PR DESCRIPTION
**Pull request by GeorgLink**

### CODE REVIEW

**Comment by jgbarah** [comment]
Very good idea, @GeorgLink.

In the case of GrimoireLab, we're going to ask students to create a repository with the staff they are producing for the evaluation. What do you think about requiring them to include a link to that repo in a fourth column in the table?

**Comment by GeorgLink** [comment]
Fourth column with link to a repository is a good idea.

**Comment by jgbarah** [comment]
I've added that fourth column, and some text explaining it. Feel free to merge if you find it convenient.

**Comment by GeorgLink** [comment]
Thanks @jgbarah

**Comment by GeorgLink** [comment]
TODO: 
- Update wiki
- Inform students

**Pull request merged**
