### PR TITLE
add information about @vchrombie

### PR DESCRIPTION
**Pull request by vchrombie**
Hello everyone
I am Venu Vardhan ([vchrombie](https://github.com/vchrombie)) and I am interested in the project idea: Implementing CHAOSS metrics with Perceval.

I am adding my information to the list of interested students through this PR.
Looking forward to work with you guys! :)

### CODE REVIEW

**Comment by vchrombie** [comment]
Actually, it is a private repository. Yesterday there was a discussion in the community call regarding the submission whether it should be through mail or a private repository. 

I am still unclear about it. Anyways, I am making it public for now. :)
Thanks!

**Comment by GeorgLink** [comment]
Thanks for clarifying. We are debating private repos on
https://github.com/chaoss/governance/issues/86

**Comment by GeorgLink** [comment]
Thanks again for making your repository public. 

We will merge your pull request once you add a link to your project proposal.

**Comment by vchrombie** [comment]
The first commit doesn't have the signature and I find fixing it, is a bit messy. So, I am closing this PR and opening a new one.

Sorry for the mess.

**Pull request closed without merging**
