### PR TITLE
Update GSoC-interest.md

### PR DESCRIPTION
**Pull request by DGomez99**
[DiegoGomezCHAOSS MicroTask.zip](https://github.com/chaoss/governance/files/6306083/DiegoGomezCHAOSS.MicroTask.zip)

[Diego Gomez CHAOSS Website Update (1).pdf](https://github.com/chaoss/governance/files/6306085/Diego.Gomez.CHAOSS.Website.Update.1.pdf)

microtask : https://docs.google.com/presentation/d/1R4nPuq2hMvR8WezMRNBIA2Q12NrPfeaBvH-yi2NYm5Y/edit?usp=sharing

proposal link : https://docs.google.com/document/d/1S3OXKxR7YyXAZ35g4zUdiRdgs0nnxT4ccZK4qqJ-uvg/edit

Signed-off-by: Julian Diego Gomez diegogomez1002@gmail.com

### CODE REVIEW

**Comment by DGomez99** [comment]
Signed-off-by: Julian Diego Gomez diegogomez1002@gmail.com

**Comment by DGomez99** [comment]
Signed-off-by: Julian Diego Gomez <diegogomez1002@gmail.com>

**Comment by DGomez99** [comment]
Signed-off-by: Julian Diego Gomez < diegogomez1002@gmail.com >

**Comment by GeorgLink** [comment]
Closing PR because it was submitted after the application deadline.

**Pull request closed without merging**
