### PR TITLE
Add information about @harshalmittal4

### PR DESCRIPTION
**Pull request by harshalmittal4**
Hello, I am interested in working upon the idea #2 [Implementing CHAOSS metrics with Perceval
](https://github.com/chaoss/wg-gmd/issues/81).
1. Added the link to the microtask repository, would update it further.
2. Would add the link to proposal once it is ready.

Thanks.
Hoping to work with you further and contributing always!

### CODE REVIEW

**Comment by vchrombie** [comment]
@harshalmittal4 
I think you forgot to sign-off the commits. You can have a look here https://github.com/chaoss/governance/blob/master/CONTRIBUTING.md#code-or-document-change-contributions-pull-request.

**Comment by harshalmittal4** [comment]
Very thanks @vchrombie for your concern regarding this.

**Comment by harshalmittal4** [comment]
Hey @valeriocos, @aswanipranjal, @jgbarah 
It would be very helpful if you can review the microtasks and suggest the improvements or changes. Please may you have a look :relaxed:.
I would be adding the link to the proposal soon, thanks!

**Comment by valeriocos** [comment]
please @harshalmittal4 could you resolve the conflicts? thanks!

**Comment by harshalmittal4** [comment]
Done.

**Comment by valeriocos** [comment]
Great thank you for the quick reaction @harshalmittal4 . 
I see that you didn't provide the link of the proposal. What do you think to link a google doc (even if empty) and work on it later? This would avoid you to make another PR to include the link to the proposal.

Any suggestions @jgbarah and @aswanipranjal ?

**Comment by valeriocos** [comment]
please squash the commits in one @harshalmittal4 and we are done :) thanks!

**Comment by harshalmittal4** [comment]
Sorry @valeriocos, can't squash them since I pulled from upstream (this repo) to my local in between accidentally, and git rebase is showing previous commits from this repo now :worried: 
I will definitely take care from next time!

**Comment by valeriocos** [comment]
no worries @harshalmittal4 . @jgbarah I guess the pr can be merged, thanks!

**Pull request merged**
