### PR TITLE
Idea for GSoC: implementing CHAOSS Metrics in Kibana Dashboards

### PR DESCRIPTION
**Pull request by alpgarcia**
Includes a tentative idea on building visualizations of CHAOSS GMD metrics and use cases using Kibana.

### CODE REVIEW

**Comment by alpgarcia** [comment]
Thanks @GeorgLink !

I've slightly modified the beginning of the second paragraph. The idea that links both paragraphs is building dashboards on top of GrimoireLab data. It could require to add new features not currently present in GrimoireLab data, so I wanted to describe the full process to let readers know what is behind the final dashboards.

**Comment by GeorgLink** [comment]
Thanks @alpgarcia

**Comment by germonprez** [comment]
@GeorgLink are you okay with this?

**Comment by GeorgLink** [comment]
Yes, I'm merging.

**Comment by GeorgLink** [comment]
@alpgarcia 
Can you please send me an email (glink@unomaha.edu) with email addresses for you and Miguel? 
We need to be able to coordinate with you.

**Pull request merged**
