### PR TITLE
Add my GSoD proposal

### PR DESCRIPTION
**Pull request by xiaoya-Esther**
Signed-off-by: Xiaoya Xia <xiaoyaxiaesther@gmail.com>

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @xiaoya-Esther 
It is easy to fix this using the command line. This following commands should work.

This will fix the sign-off on the last commit. 
```
$ git commit --amend --signoff
```

This will push the changes (here, it is only the sign-off).
```
$ git push --force-with-lease origin patch-2
```

Let us know if you need any help. :smile:

**Comment by xiaoya-Esther** [comment]
I think I get the workflow now:) Thanks!

**Comment by vchrombie** [comment]
> And since this was first initiated on GitHub, I should clone the branch `patch-2` locally first, then amend the sign-off, right?

yes, exactly. :slightly_smiling_face: 

> I think I get the workflow now:) Thanks!

It looks perfect. Good work on the sign-off @xiaoya-Esther. :+1:

**Comment by vchrombie** [comment]
Hi @xiaoya-Esther 
Can you please resolve the merge conflicts if possible?

Let me know if you need any help. :slightly_smiling_face:

**Comment by GeorgLink** [comment]
Thanks @xiaoya-Esther

**Comment by xiaoya-Esther** [comment]
> Hi @xiaoya-Esther
> Can you please resolve the merge conflicts if possible?
> 
> Let me know if you need any help. 🙂

Sorry, @vchrombie I just saw this message, thanks for the merge!

**Pull request merged**
