### PR TITLE
Added my GSoD Proposal

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
Signed-off-by: Jaskirat Singh <juskirat2000@gmail.com>

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @jaskiratsingh2000 

I think you missed the sign-off. 
You need not close the PR. I'll add a few steps to fix this. 

```
$ git commit --amend --signoff
$ git push -f origin branch_name
```

Let me know if you need any help. :smile:

**Comment by jaskiratsingh2000** [comment]
Any way to do it without Git? I don't use it

**Comment by tharun143** [comment]
Yes @jaskiratsingh2000 , you can do it in multiple ways. 😬

(easy) You can use this extension, scottrigby/dco-gh-ui
(medium) While committing, you can add the sign-off string in the description box under the commit title
(hard) Clone the repository and the branch and sign-off using command and force push
😄
You can always go for the first option. Just install the extension, it will take care of the sign-off.

credits - @vchrombie

**Comment by GeorgLink** [comment]
I use a browser plugin: https://github.com/scottrigby/dco-gh-ui

The easiest would be to (1) install the plugin and configure it, (2) close this PR, and (3) create a new PR with the DCO sign-off.

**Pull request closed without merging**
